# Generated by Django 4.1.5 on 2023-03-08 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSAndCMetrics',
            fields=[
                ('s_and_c_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_s_and_c_metrics',
            },
        ),
        migrations.CreateModel(
            name='UserErgMetrics',
            fields=[
                ('erg_metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.CharField(max_length=10)),
                ('strokes_per_minute', models.IntegerField()),
                ('split_500m', models.DurationField()),
                ('time', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_erg_metrics',
            },
        ),
    ]
