# Generated by Django 4.1.5 on 2023-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_gathering_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userergmetrics',
            name='split_500m',
            field=models.DurationField(null=True),
        ),
    ]
