# Generated by Django 4.1.5 on 2023-03-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_gathering_app', '0003_alter_userergmetrics_split_500m'),
    ]

    operations = [
        migrations.AddField(
            model_name='userergmetrics',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersandcmetrics',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
