# Generated by Django 4.1.5 on 2023-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_gathering_app', '0004_userergmetrics_date_usersandcmetrics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userergmetrics',
            name='split_500m',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userergmetrics',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
