# Generated by Django 4.1.5 on 2023-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_gathering_app', '0005_alter_userergmetrics_split_500m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userergmetrics',
            name='time_in_seconds',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
