# Generated by Django 4.1.5 on 2023-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_gathering_app', '0006_userergmetrics_time_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userergmetrics',
            name='strokes_per_minute',
            field=models.IntegerField(null=True),
        ),
    ]
