# Generated by Django 4.1.5 on 2023-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_gathering_app', '0007_alter_userergmetrics_strokes_per_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userergmetrics',
            name='intensity_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
