# Generated by Django 4.1.5 on 2023-03-01 11:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRowingInfo',
            fields=[
                ('user_rowing_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('coaches', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('race_category', models.CharField(max_length=50)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('wingspan', models.IntegerField(null=True)),
                ('development_rating', models.CharField(choices=[('Elite', 'Elite'), ('Pre-Elite', 'Pre-Elite'), ('Developmental', 'Developmental')], max_length=13, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'athlete_info',
            },
        ),
        migrations.CreateModel(
            name='UserPersonalBests',
            fields=[
                ('user_pb_id', models.AutoField(primary_key=True, serialize=False)),
                ('pb_100', models.DurationField()),
                ('pb_500', models.DurationField()),
                ('pb_1000', models.DurationField()),
                ('pb_2000', models.DurationField()),
                ('pb_6000', models.DurationField()),
                ('pb_10000', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'athlete_personal_bests',
            },
        ),
    ]
