# Generated by Django 4.1.5 on 2023-02-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpersonalbests',
            table='athlete_personal_bests',
        ),
        migrations.AlterModelTable(
            name='userrowinginfo',
            table='athlete_info',
        ),
    ]
