# Generated by Django 4.1.5 on 2023-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details_app', '0002_userprofilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='profile_picture',
            field=models.BinaryField(),
        ),
    ]
