# Generated by Django 4.1.5 on 2023-03-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details_app', '0003_alter_userprofilepicture_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrowinginfo',
            old_name='club_names',
            new_name='clubs',
        ),
    ]
