# Generated by Django 4.1.5 on 2023-03-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details_app', '0004_rename_club_names_userrowinginfo_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
