# Generated by Django 4.1.5 on 2023-03-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details_app', '0005_alter_userprofilepicture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
