# Generated by Django 4.1.5 on 2023-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details_app', '0006_alter_userprofilepicture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalbests',
            name='pb_100',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpersonalbests',
            name='pb_1000',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpersonalbests',
            name='pb_10000',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpersonalbests',
            name='pb_2000',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpersonalbests',
            name='pb_500',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpersonalbests',
            name='pb_6000',
            field=models.CharField(max_length=20),
        ),
    ]
