# Generated by Django 4.1.5 on 2023-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('club_nickname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rowing_club_info',
            },
        ),
        migrations.CreateModel(
            name='RaceCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('max_age', models.IntegerField()),
                ('required_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('max_weight', models.IntegerField()),
            ],
            options={
                'db_table': 'race_categories',
            },
        ),
    ]
