# Generated by Django 4.1.5 on 2023-02-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_dropdown_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='racecategory',
            table='rowing_race_categories',
        ),
    ]
