# Generated by Django 4.1.5 on 2023-03-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_dropdown_data_app', '0002_alter_racecategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecategory',
            name='category_nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
