# Generated by Django 4.1.5 on 2023-02-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0003_user_is_athlete_user_is_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
