# Generated by Django 4.1.5 on 2023-02-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0005_alter_user_password_userrowinginfoathletedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRowingInfoAthleteDetails',
        ),
    ]
